### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/col-debug-tools#1]
@mdoering 
could you please tell me what pages you envision?

Suggestions:

* name search (with filters) - a list of names in various datasets. Links to a taxon?
* taxon page http://api.col.plus/taxon/1123282 with various links to synonyms, its classification and its children.
* taxon tree page where you select a dataset first
* dataset search page
* dataset page (not really any content here but a link to name search and tree)

All pages link to their API counterpart

**Comment by mdoering** [comment]
That sounds about right, Morten.

- DATASET SEARCH or as a start just a plain list of all dataset titles linking to the dataset details
- DATASET DETAIL showing all of http://api.col.plus/dataset/10 plus the latest successful import details (json dump) and a list of all imports (state, started date, verbatim count). If could also list all root taxa of the tree
- NAME SEARCH (with filters) listing names and potentially their accepted names (plural) in case of synonyms. Good enough here to show the name as _scientificName_ in italics plus authorship in regular font. Plus rank and maybe code (to coarsely differ between plants and animals)
- TAXON DETAIL showing the Taxon with Name, TaxonInfo (common names & distributions), Synonymy and Classification. Basic tables or lists for the common names and distributions maybe, but JSON dumps would also do. Link to basionym (kinda difficult as it is cause its a name key that needs resolved via taxon?nameKey first to link to one or more taxa). Instead of a dedicated tree browser I could also imagine just a plain list of children at the bottom

**Comment by MortenHofft** [comment]
NAME SEARCH
Nom code: Could you give me an example from the name/search API please?

**Comment by MortenHofft** [comment]
TAXON DETAIL
Could you give an example from the API. what taxon should link to what other taxon and what URLS to call to get the key please. If it is something that is considered essential for a taxon - then perhaps it should be included in the result?

**Comment by mdoering** [comment]
TAXON DETAIL:

- for the Name a link to its basionym if existing. So if taxon.name.basionymKey is present link to the taxon retrieved by /taxon?nameKey={basionymKey}
- show classification, each taxon with a link
